variable "namespace" {
  description = "Kubernetes namespace where the Dragonfly instance is created."
  type        = string
}

variable "name" {
  description = "Dragonfly instance name. Clients connect to the operator-managed `<name>` Service (repointed to the master on failover)."
  type        = string
  default     = "dragonfly"
}

variable "part_of" {
  description = "Value of the app.kubernetes.io/part-of label on the managed resources."
  type        = string
  default     = null
}

variable "replicas" {
  description = "Total instances (master + replicas). 2 = master + 1 replica with operator-managed automatic failover; 1 = single instance, no HA. Anti-affinity needs at least as many nodes as replicas."
  type        = number
  default     = 2

  validation {
    condition     = var.replicas >= 1
    error_message = "replicas must be >= 1."
  }
}

variable "image" {
  description = "Dragonfly image. null lets the operator pick its default."
  type        = string
  default     = null
}

# --- resources ---------------------------------------------------------------
# Dragonfly is multi-threaded and refuses to start with less than ~256Mi per
# io-thread, so memory and threads are coupled here and validated together.

variable "threads" {
  description = "Dragonfly io-threads (--proactor_threads). 1 keeps the memory floor predictable for a cache; raise it (with memory) for throughput."
  type        = number
  default     = 1

  validation {
    condition     = var.threads >= 1
    error_message = "threads must be >= 1."
  }
}

variable "memory_mib" {
  description = "Pod memory request/limit in MiB (Dragonfly sets maxmemory to ~80% of it). Must be at least 256 MiB per thread or Dragonfly will not start."
  type        = number
  default     = 512

  validation {
    condition     = var.memory_mib >= var.threads * 256
    error_message = "memory_mib must be at least 256 per thread (threads * 256), or Dragonfly will not start."
  }
}

variable "cpu_requests" {
  description = "CPU request per pod."
  type        = string
  default     = "100m"
}

# --- auth --------------------------------------------------------------------

variable "auth" {
  description = "Protect the instance with a password (generated by Terraform). When true, REDIS_URL (with the password) is in sensitive_env; when false it is plaintext in env."
  type        = bool
  default     = true
}

# --- backup / persistence ----------------------------------------------------

variable "snapshot" {
  description = <<-EOT
    Periodic snapshots. Set `s3_uri` for keyless S3 backups (the pods write
    with their ambient IAM identity via EKS Pod Identity / IRSA — pair it with
    `service_account_name` and an association on the cluster). Set `pvc_size`
    for local PVC-backed persistence instead. Leave null to disable snapshots.
  EOT
  type = object({
    s3_uri   = optional(string) # s3://<bucket>/<path> (keyless via Pod Identity)
    pvc_size = optional(string) # e.g. "5Gi" for a local snapshot PVC
    cron     = optional(string, "0 */6 * * *")
  })
  default = null

  validation {
    condition     = var.snapshot == null || (var.snapshot.s3_uri != null) != (var.snapshot.pvc_size != null)
    error_message = "Set exactly one of snapshot.s3_uri or snapshot.pvc_size."
  }
}

variable "service_account_name" {
  description = "ServiceAccount for the instance pods (created by this module). Needed for keyless S3 snapshots via Pod Identity/IRSA. null uses the operator default."
  type        = string
  default     = null
}

variable "service_account_annotations" {
  description = "Annotations for the created ServiceAccount (e.g. the IRSA `eks.amazonaws.com/role-arn` when not using Pod Identity)."
  type        = map(string)
  default     = {}
}

# --- metadata / scheduling ---------------------------------------------------

variable "labels" {
  description = "Extra labels added to the instance and propagated to the objects the operator creates."
  type        = map(string)
  default     = {}
}

variable "annotations" {
  description = "Annotations propagated to the objects the operator creates."
  type        = map(string)
  default     = {}
}

variable "node_selector" {
  description = "nodeSelector for the instance pods."
  type        = map(string)
  default     = {}
}

variable "tolerations" {
  description = "Tolerations for the instance pods."
  type        = list(any)
  default     = []
}

variable "topology_spread_constraints" {
  description = "topologySpreadConstraints for the instance pods (spread master/replica across nodes)."
  type        = any
  default     = []
}

# --- readiness ---------------------------------------------------------------

variable "wait_for_ready" {
  description = "Block the apply until the operator reports the instance Ready. Off by default; consumers usually gate on their own probe."
  type        = bool
  default     = false
}

variable "ready_timeout" {
  description = "How long to wait for the Ready phase when wait_for_ready is set."
  type        = string
  default     = "6m"
}
